# ECS 171 Project
Briana Fedkiw, Ray Zhu, Sam Xie, Vikram Karmarkar

# Preprocessing

# Logistic Regression Modelling

In [2]:
import numpy as np
import pandas as pd

raw_data = pd.read_csv("mushroom/agaricus-lepiota.data")
display(raw_data)
display(raw_data.describe())

      p  x  s  n  t p.1  f  c n.1  k  ... s.2  w w.1 p.2 w.2  o p.3 k.1 s.3  u
0     e  x  s  y  t   a  f  c   b  k  ...   s  w   w   p   w  o   p   n   n  g
1     e  b  s  w  t   l  f  c   b  n  ...   s  w   w   p   w  o   p   n   n  m
2     p  x  y  w  t   p  f  c   n  n  ...   s  w   w   p   w  o   p   k   s  u
3     e  x  s  g  f   n  f  w   b  k  ...   s  w   w   p   w  o   e   n   a  g
4     e  x  y  y  t   a  f  c   b  n  ...   s  w   w   p   w  o   p   k   n  g
...  .. .. .. .. ..  .. .. ..  .. ..  ...  .. ..  ..  ..  .. ..  ..  ..  .. ..
8118  e  k  s  n  f   n  a  c   b  y  ...   s  o   o   p   o  o   p   b   c  l
8119  e  x  s  n  f   n  a  c   b  y  ...   s  o   o   p   n  o   p   b   v  l
8120  e  f  s  n  f   n  a  c   b  n  ...   s  o   o   p   o  o   p   b   c  l
8121  p  k  y  n  f   y  f  c   n  b  ...   k  w   w   p   w  o   e   w   v  l
8122  e  x  s  n  f   n  a  c   b  y  ...   s  o   o   p   o  o   p   o   c  l

[8123 rows x 23 columns]

,p,x,s,n,t,p.1,f,c,n.1,k,...,s.2,w,w.1,p.2,w.2,o,p.3,k.1,s.3,u
count,8123,8123,8123,8123,8123,8123,8123,8123,8123,8123,...,8123,8123,8123,8123,8123,8123,8123,8123,8123,8123
unique,2,6,4,10,2,9,2,2,2,12,...,4,9,9,1,4,3,5,9,6,7
top,e,x,y,n,f,n,f,c,b,b,...,s,w,w,p,w,o,p,w,v,d
freq,4208,3655,3244,2283,4748,3528,7913,6811,5612,1728,...,4935,4463,4383,8123,7923,7487,3967,2388,4040,3148

## Validation and Testing

### 10-fold Cross validation

In [1]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

NameError: name 'X' is not defined

In [2]:
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, accuracy_score

# Split data into 10 folds
kf = KFold(n_splits=10)
accuracy, mse = np.zeros(kf.get_n_splits(X_train)), np.zeros(kf.get_n_splits(X_train))
for i, (train_index, test_index) in enumerate(kf.split(X_train)):
    train_index = slice(train_index[0], train_index[-1] + 1)
    test_index = slice(test_index[0], test_index[-1] + 1)

    model.fit(X_train[train_index], y_train[train_index])
    pred = model.predict(X_train[test_index])
    accuracy[i] = accuracy_score(y_train[test_index], pred)
    mse[i] = mean_squared_error(y_train[test_index], pred)

# Display the performance of each fold and the overall average
performance_df = pd.DataFrame(np.transpose([np.arange(1, len(mse)+1), accuracy, mse]), columns=["Iteration", "Accuracy", "MSE"]).set_index("Iteration")
display(performance_df)
print(f"Average accuracy = {np.average(accuracy)}")
print(f"Average MSE = {np.average(mse)}")

NameError: name 'np' is not defined

In [2]:
pred = model.predict(y_test)

### Confusion matrix

In [ ]:
from sklearn.metrics import classification_report, multilabel_confusion_matrix


print("Confusion matrix values for each label:")
mcm = multilabel_confusion_matrix(y_test, pred)
confusion_df = pd.DataFrame(data=[[f"quality_{i+1}", mcm[i, 1, 1], mcm[i, 0, 1], mcm[i, 1, 0], mcm[i, 0, 0]]
    for i, matrix in enumerate(mcm)],
    columns=["Label", "TP", "FP", "FN", "TN"]).set_index("Label")
display(confusion_df)

### Classification report

In [ ]:
from sklearn.metrics import mean_squared_error, accuracy_score

print("Classification report:")
print(classification_report(y_test, pred, zero_division=0.0))

print("\nModel data:")
print(f"Accuracy: {accuracy_score(y_test, pred)}")
print(f"MSE: {mean_squared_error(y_test, pred)}\n")